env:
  TERM: xterm-256color
window:
  padding:
    x: 8
    y: 12
  decorations_theme_variant: Dark
  decorations: buttonless
  option_as_alt: OnlyLeft
font:
  normal:
    family: FiraMono Nerd Font Propo
    style: Regular
  bold:
    family: FiraMono Nerd Font Propo
    style: bold
  italic:
    family: FiraMono Nerd Font Propo 
    style: Italic
  bold_italic:
    family: FiraMono Nerd Font Propo 
    style: Bold Italic
  size: 13.0
  offset:
    y: 8 
    x: 0
import:
  - ~/.config/alacritty/rose-pine.yml
bell:
  duration: 10
  animation: EaseOutExpo
cursor:
  style:
    shape: Block
    blinking: On
  blink_interval: 500
  unfocused_hollow: true
key_bindings:
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: F, mods: Command, action: SearchForward }
  - { key: F, mods: Command|Shift, action: SearchBackward }

    # Command + , for preferences on macOS
  - key: Comma
    mods: Command
    command:
      program: tmux
      args:
        - popup
        - -E
        - -w 50%
        - -h 50%
        - nvim ~/.config/alacritty/alacritty.yml
